In [1]:
# This program should get the data from a excel files and extract the specific Data
import pandas as pd
import numpy as np
import glob as glb


To get the Header data in we should put the header as None

In [2]:
data = pd.read_excel("G:\Google\Electronic Design\python_projects\Insight of Ecommerce Data/2020\sep.xls",
                    sheet_name= "orders",
                    header = None,
                    index_col= None)
data_np = data.to_numpy()

In [3]:
list_interest=['Receiver Name','Phone Number', 'Area', 'State', 'Zip Code']

In [4]:
loc2 = []
for i in list_interest:
    loc = np.argwhere(data_np == i)
    print(loc)
    loc2.append(loc[0])
type(loc2)

[[ 0 42]]
[[ 0 43]]
[[ 0 47]]
[[ 0 48]]
[[ 0 50]]


list

In [8]:
glb.glob('G:\Google\Electronic Design\python_projects\Insight of Ecommerce Data/2020\*')

['G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Apr.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Aug.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Jul.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Jun.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Mar.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\May.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Oct.xls',
 'G:\\Google\\Electronic Design\\python_projects\\Insight of Ecommerce Data/2020\\Sep.xls']

Y is the number of ROWs and X is the number of culomns 

In [5]:
[y, x] = data_np.shape
print(' Row = {}, COL = {}'.format(y,x))

 Row = 327, COL = 54


Collect the relevent data from the database.

In [6]:
info = []
for i in loc2:
    info.append(data_np[1:y, i[1]])

Here we will combine two datas and create a dictionary to be saved in Excel file

In [7]:
dic = dict(zip(list_interest, info))
panda_dic = pd.DataFrame(dic)

In [128]:
writer = pd.ExcelWriter('Extracted_Data.xlsx', engine='xlsxwriter')

In [129]:
panda_dic.to_excel(writer, 'Sheet1')
writer.save()

In [67]:
f = False
for i in range(0,326):
    for j in range(0,54):
        if data_np[i,j] == "2009170BKTP73A":
            print("found one")
            print("location is ({},{})".format(i, j))
            f = True
if f == False:
    print("There is no sign of titles")

found one
location is (182,0)


In [68]:
if "Order ID" in data_np:
    print("We found the data")

We found the data


In [69]:
x, y = np.where(data_np == "2009170BKTP73A")
loc = list(zip(x, y))
print(loc)

[(182, 0)]


In [70]:
loc = np.argwhere(data_np == "Order ID")
print(loc)

[[0 0]]


In [83]:
data_np[0,50]

'Zip Code'

In [42]:
dic = dict(i in list_interest, )

181